FROM docker.io/fedora:37

RUN dnf update -y && \
    dnf install -y  \
	containers-common device-mapper-devel git glib2-devel glibc-devel \
	glibc-static go gpgme-devel libassuan-devel libgpg-error-devel \
	libseccomp-devel libselinux-devel pkgconfig make runc btrfs-progs-devel \
	rpm-build go-md2man go-rpm-macros
ADD _rpmmacros /root/.rpmmacros
